In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
## Define the vocabulary size
voc_size=10000

In [6]:
# One hot representation 
one_hot_repr = [one_hot(words,voc_size) for words in sent]
one_hot_repr

[[6013, 4150, 3549, 1878],
 [6013, 4150, 3549, 6475],
 [6013, 2815, 3549, 5120],
 [9922, 3727, 302, 8655, 1515],
 [9922, 3727, 302, 8655, 9666],
 [2262, 6013, 5834, 3549, 1360],
 [481, 9220, 3812, 8655]]

In [7]:
# word embedding representation 
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [8]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 6013 4150 3549 1878]
 [   0    0    0    0 6013 4150 3549 6475]
 [   0    0    0    0 6013 2815 3549 5120]
 [   0    0    0 9922 3727  302 8655 1515]
 [   0    0    0 9922 3727  302 8655 9666]
 [   0    0    0 2262 6013 5834 3549 1360]
 [   0    0    0    0  481 9220 3812 8655]]


In [9]:
dim = 10

In [10]:
model = Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam', 'mse')

In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [12]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 175ms/step


array([[[-4.0073767e-03,  7.9721212e-07, -3.5616674e-02, -5.7796836e-03,
         -4.3344982e-03, -4.7712434e-02, -4.9886219e-03,  1.5711341e-02,
          4.2865466e-02, -2.7216449e-03],
        [-4.0073767e-03,  7.9721212e-07, -3.5616674e-02, -5.7796836e-03,
         -4.3344982e-03, -4.7712434e-02, -4.9886219e-03,  1.5711341e-02,
          4.2865466e-02, -2.7216449e-03],
        [-4.0073767e-03,  7.9721212e-07, -3.5616674e-02, -5.7796836e-03,
         -4.3344982e-03, -4.7712434e-02, -4.9886219e-03,  1.5711341e-02,
          4.2865466e-02, -2.7216449e-03],
        [-4.0073767e-03,  7.9721212e-07, -3.5616674e-02, -5.7796836e-03,
         -4.3344982e-03, -4.7712434e-02, -4.9886219e-03,  1.5711341e-02,
          4.2865466e-02, -2.7216449e-03],
        [ 2.6572432e-02,  4.4969525e-02,  6.0733072e-03, -4.8043597e-02,
          2.1454882e-02,  4.6615455e-02, -3.2574967e-02,  3.2808449e-02,
          3.3281092e-02, -9.9079609e-03],
        [ 2.2587288e-02, -9.4091892e-04, -6.7209117e-03,  3.

In [13]:
embedded_docs[0]

array([   0,    0,    0,    0, 6013, 4150, 3549, 1878], dtype=int32)

In [14]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 55ms/step


array([[-4.0073767e-03,  7.9721212e-07, -3.5616674e-02, -5.7796836e-03,
        -4.3344982e-03, -4.7712434e-02, -4.9886219e-03,  1.5711341e-02,
         4.2865466e-02, -2.7216449e-03],
       [-4.0073767e-03,  7.9721212e-07, -3.5616674e-02, -5.7796836e-03,
        -4.3344982e-03, -4.7712434e-02, -4.9886219e-03,  1.5711341e-02,
         4.2865466e-02, -2.7216449e-03],
       [-4.0073767e-03,  7.9721212e-07, -3.5616674e-02, -5.7796836e-03,
        -4.3344982e-03, -4.7712434e-02, -4.9886219e-03,  1.5711341e-02,
         4.2865466e-02, -2.7216449e-03],
       [-4.0073767e-03,  7.9721212e-07, -3.5616674e-02, -5.7796836e-03,
        -4.3344982e-03, -4.7712434e-02, -4.9886219e-03,  1.5711341e-02,
         4.2865466e-02, -2.7216449e-03],
       [ 2.6572432e-02,  4.4969525e-02,  6.0733072e-03, -4.8043597e-02,
         2.1454882e-02,  4.6615455e-02, -3.2574967e-02,  3.2808449e-02,
         3.3281092e-02, -9.9079609e-03],
       [ 2.2587288e-02, -9.4091892e-04, -6.7209117e-03,  3.8403872e-02,
   